3Stones-io/omedis

.github/workflows/ci.yml, config/deploy.yml
Resolves #381.
You can see it in action: https://github.com/3Stones-io/omedis/actions/runs/12047182367.
=> Continuous delivery

priv/repo/demo_seeds.exs
=> Add invitation access rights

lib/omedis/accounts/checks/can_delete_account.ex, test/omedis/user_test.exs, test/omedis_web/live/edit_profile_test.exs
=> Prevent the sole administrator from deleting their account

coveralls.json, lib/omedis/accounts/group.ex, lib/omedis/accounts/project.ex, lib/omedis_web/live/organisation_live/today.ex, priv/gettext/de/LC_MESSAGES/group.po, priv/gettext/de/LC_MESSAGES/organisation.po, priv/gettext/de/LC_MESSAGES/project.po, priv/gettext/en/LC_MESSAGES/group.po, priv/gettext/en/LC_MESSAGES/organisation.po, priv/gettext/en/LC_MESSAGES/project.po, priv/gettext/fr/LC_MESSAGES/group.po, priv/gettext/fr/LC_MESSAGES/organisation.po, priv/gettext/fr/LC_MESSAGES/project.po, priv/gettext/group.pot, priv/gettext/it/LC_MESSAGES/group.po, priv/gettext/it/LC_MESSAGES/organisation.po, priv/gettext/it/LC_MESSAGES/project.po, priv/gettext/organisation.pot, priv/gettext/project.pot, test/omedis/accounts/group_test.exs, test/omedis/project_test.exs, test/omedis_web/live/organisation_live/today_test.exs
=> Refactor code for fetching latest group and project in today live

lib/omedis_web/components/general_components.ex
Fixes #439.
https://github.com/user-attachments/assets/3f6593f3-f958-4d35-879c-b41b8a30fc38
=> Make breadcrumbs fully responsive

lib/omedis_web/components/core_components.ex, lib/omedis_web/live/invitation_live/show.ex
Fixes #436 
https://github.com/user-attachments/assets/9e75eb72-dea9-494b-b1c2-148e7eeef62b
=> Disable editing on invitation email field

lib/omedis_web/components/general_components.ex
=> Remove duplicate link

lib/omedis_web/components/general_components.ex
Fixes #438 
https://github.com/user-attachments/assets/38feff69-4c08-43cc-88af-948a61ec8333
=> Fix register links visibility on small screens

lib/omedis_web/live/organisation_live/today.ex
Fixes #440.
Before fixing👇
https://github.com/user-attachments/assets/dd02c03e-cdb8-4f9f-bf42-50423f08128a
After 👇
https://github.com/user-attachments/assets/82699444-2bfe-408d-b30f-4838154b146c
=> Stop unnecessary database polling on Today LiveView

coveralls.json, lib/omedis_web/live/invitation_live/show.ex, test/omedis_web/live/invitation_live/show_test.exs
=> Bugfix: Pass `current_organisation_id` when registering invited users

lib/omedis/accounts/project.ex, lib/omedis_web/live/project_live/index.ex, test/omedis_web/live/project_live/index_test.exs
Resolves #481.
https://github.com/user-attachments/assets/49fba196-b4c8-424f-95ec-7cacdd49f2c5
=> Propagate Project changes to the UI in realtime

config/config.exs, lib/omedis/accounts.ex, lib/omedis/accounts/activity.ex, lib/omedis/accounts/organisation.ex, lib/omedis/accounts/organisation/changes/create_organisation_defaults.ex, lib/omedis/fixtures.ex, lib/omedis/projects.ex, lib/omedis/projects/project.ex, lib/omedis/projects/project/relationships/project_access_rights.ex, lib/omedis_web/live/activity_live/index.ex, lib/omedis_web/live/activity_live/show.ex, lib/omedis_web/live/organisation_live/today.ex, lib/omedis_web/live/project_live/form_component.ex, lib/omedis_web/live/project_live/index.ex, lib/omedis_web/live/project_live/show.ex, priv/repo/demo_seeds.exs, priv/repo/personas_seeds.exs, test/omedis/accounts/accounts_test.exs, test/omedis/accounts/organisation_test.exs, test/omedis/projects/project_test.exs, test/omedis/projects/projects_test.exs, test/omedis_web/live/organisation_live/today_test.exs, test/omedis_web/live/project_live/index_test.exs
=> Projects domain

lib/omedis/invitations/invitation/changes/ensure_expiration_is_in_future.ex
=> Fix invitation expiry datetime comparison

.github/workflows/ci.yml, CONTRIBUTING.md, Makefile, README.md, mix.exs, priv/repo/personas_seeds.exs, priv/repo/seeds.exs
=> Seeds check

assets/css/app.css, assets/tailwind.config.js, coveralls.json, lib/omedis_web/components/calendar_components.ex, lib/omedis_web/components/time_tracking.ex, lib/omedis_web/live/playground_live.ex
Fixes #470 . 
The buttons functionality should be added when the implementation of the chat(maybe) is done as that will need some backend interaction.
=> New message notification component

lib/omedis/access_rights.ex, lib/omedis/access_rights/access_right.ex, lib/omedis/accounts/organisation/changes/create_organisation_defaults.ex
=> Move access_rights code interface to domain

lib/omedis_web/components/general_components.ex, lib/omedis_web/live/organisation_live/show.ex, lib/omedis_web/live/time_tracker_live/index.ex
Fixes #508 
https://github.com/user-attachments/assets/ddf812fc-0105-4901-a9c5-2f24a9e78d29
=> Fix timer breaking when one navigates to other pages

lib/omedis_web/live/register_live.ex, priv/gettext/auth.pot, priv/gettext/de/LC_MESSAGES/auth.po, priv/gettext/en/LC_MESSAGES/auth.po, priv/gettext/fr/LC_MESSAGES/auth.po, priv/gettext/it/LC_MESSAGES/auth.po, test/omedis_web/live/register_test.exs
=> Fix incorrect translation for email instruction

lib/omedis/time_tracking/event.ex, lib/omedis_web/live/event_live/index.ex, test/omedis/time_tracking/time_tracking_test.exs
Fixes #480 
https://github.com/user-attachments/assets/4e745da5-5ebe-4d76-b1ec-d361b0ca70bb
=> Broadcast event created and updated messages

lib/omedis_web/live/time_tracker_live/index.ex, test/omedis_web/live/organisation_live/show_test.exs
=> Ensure time tracker doesn't count down to negative values

lib/omedis_web/components/time_tracking.ex
=> Remove timer on today live

coveralls.json, test/omedis_web/live/invitation_live/show_test.exs, test/omedis_web/live/login_test.exs, test/omedis_web/live/register_test.exs
=> Improve user registration and login test flow

mix.exs
=> Add mix compile to CI check

lib/omedis_web/components/general_components.ex, lib/omedis_web/router.ex, priv/gettext/de/LC_MESSAGES/navigation.po, priv/gettext/en/LC_MESSAGES/navigation.po, priv/gettext/fr/LC_MESSAGES/navigation.po, priv/gettext/it/LC_MESSAGES/navigation.po, priv/gettext/navigation.pot
=> Add Playground in all environments

assets/css/app.css, assets/js/app.js, assets/tailwind.config.js, coveralls.json, lib/omedis_web/components/client_doctor_form_components.ex, lib/omedis_web/components/layouts/root.html.heex, lib/omedis_web/live/playground_live.ex, priv/gettext/de/LC_MESSAGES/navigation.po, priv/gettext/en/LC_MESSAGES/navigation.po, priv/gettext/fr/LC_MESSAGES/navigation.po, priv/gettext/it/LC_MESSAGES/navigation.po, priv/gettext/navigation.pot
Fixes #561 
https://github.com/user-attachments/assets/8b65c467-5de1-4ae7-9736-eda1ad577885
=> Create client form navigation component

lib/omedis_web/live/login_live.ex, test/omedis_web/live/login_test.exs
=> fix login button text

coveralls.json, lib/omedis_web/live/playground_live/client_doctor_forms.ex, lib/omedis_web/live/playground_live/index.ex, lib/omedis_web/router.ex
=> Create a links landing page for playground pages
